<?php include('includes/sqlConnection.php');?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Name of Website - Home</title>
<link rel="stylesheet" href="css/webDesign.css" />

</head>
<header>
	<?php include('includes/header.php');?>
</header>
<body>
    <div id="container">
        <div id="content">
        HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT AND SOME MORE TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT HERES SOME TEXT 
        </div>
    </div>
</body>
<footer>
    <?php include('includes/footer.php');?>
</footer>
</html>